# Vanilla Tmux Configuration

# Split Navigation
# Standard prefix is Ctrl-b
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse support for easier interaction
set -g mouse on
